### ISSUE TITLE
[Windows] Input dialog closes

### ISSUE THREAD

**Issue by tlgreg** [patbenatar/vscode-advanced-new-file#16] opened 2017-02-27 12:12 UTC
Advanced New File dialog closes in a second or so after opening (both with keyboard shortcut or starting from command palette).

Can't provide much else to the problem, no errors or output by the extension, nothing in devtools console.

VSC is 1.10.0-insider on windows.

**Comment by Kaffiend** [comment] 2017-03-05 15:42
having the same issue. i really prefer this method of new files compared to the similar extensions in the market place.

**Comment by patbenatar** [comment] 2017-03-05 15:47
@Kaffiend are you also on windows? What version of VS Code?

**Comment by Kaffiend** [comment] 2017-03-05 15:48
I am dual boot windows 10, i think its on my linux as well, i can check in a bit.
vscode --v : 1.10.1

**Comment by patbenatar** [comment] 2017-03-05 15:56
Thanks!

Are you both on the latest version of the plugin?

**Comment by Kaffiend** [comment] 2017-03-05 15:56
I am, i just reinstalled to confirm.

**Comment by Kaffiend** [comment] 2017-03-06 04:05
I finally got a chance to take a look at linux. Linux is not affected.

**Comment by patbenatar** [comment] 2017-03-06 04:10
Thanks @Kaffiend — my primary machine is a Mac and it's not affected. Looks like we've isolated it to a Win issue. I'll debug further when I'm at my Win machine.

**Comment by seadynamic8** [comment] 2017-03-20 15:13
I just wanted to put in another notice that I also have run into the same problem on Windows. (with version 0.4.0 of ANF and 1.10.2 of VSC)

Works fine on Linux.  Don't have a Mac, so can't test there.

**Comment by patbenatar** [comment] 2017-03-20 16:34
Thanks @seadynamic8 .. I unfortunately haven't had a chance to debug on my Windows machine. If anyone here wants to help out with that, would be much appreciated :)

**Comment by tlgreg** [comment] 2017-03-24 07:12
Just a tiny update, cause I couldn't debug, just re-enabled the extension today to check, currently vscode is on 1.11.0-insider, now the dialog doesn't close, but when trying to select an existing path it loads infinitely, existing paths doesn't show.

**Comment by tlgreg** [comment] 2017-03-24 07:48
Ok, found the problem. It's in `walkupGitignores`, systemRoot returns the root in capital, while path.resolve returns the drive letter in a small case, so it's an infinite loop.

**Comment by patbenatar** [comment] 2017-03-24 22:08
Thanks @tlgreg ! Fixed in #19 — will push out a release soon

**Comment by patbenatar** [comment] 2017-03-24 22:35
Fixed in 0.4.1

**Comment by Kaffiend** [comment] 2017-03-27 22:45
Windows 10 X64 still closes automatically. Linux still fine.

**Comment by patbenatar** [comment] 2017-04-02 16:04
@Kaffiend I'm unable to reproduce the issue on my Windows 10 machine. Can you try building the project on your machine? If you're able to reproduce off the `master` branch then we can begin debugging on your system. See https://github.com/patbenatar/vscode-advanced-new-file#contributing for setup instructions

**Comment by Kaffiend** [comment] 2017-04-02 16:31
I havent tried the master branch yet, just the latest in the market. Ill
check it out.

**Comment by patbenatar** [comment] 2017-04-02 16:40
Thanks @Kaffiend !

**Comment by Kaffiend** [comment] 2017-04-05 16:11
ok finally getting a breather moment to try this, ill let you know here shortly. Sorry been swamped.

**Comment by Kaffiend** [comment] 2017-04-05 16:22
Still closes without any message..

on the directories function we are getting a max call stack on the reject.

**Comment by Kaffiend** [comment] 2017-04-05 16:47
the `walkupGitignores` function is walking from the root of the drive, not root of workspace. why would you want to start at the root and not the root of the workspace? Not convinced this is the entire issue, but seems rather inefficient??

**Comment by Kaffiend** [comment] 2017-04-05 17:03
Found the problem..or problem at least.
[this](https://github.com/patbenatar/vscode-advanced-new-file/blob/master/src/extension.ts#L11) returns the node process cwd, problem is, the root workspace may not be on the same drive. Windows node is installed and runs from C:\ and is accessed through path variable on other drives. I do all my development on a separate ssd from my OS which is D:\

**Comment by Kaffiend** [comment] 2017-04-05 18:41
Ok got my head wrapped around this extension a little better now. I'll issue a PR here soon with the fix

**Comment by patbenatar** [comment] 2017-04-06 19:16
@Kaffiend thanks! I commented on the PR

**Comment by patbenatar** [comment] 2017-04-18 16:49
Should be fixed in 0.4.3

**Closed by patbenatar** 2017-04-18 16:49 UTC
